src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CommentaireRepository::class)
 */
class Commentaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=55)
     */
    private $Pseudo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateTime;

    /**
     * @ORM\Column(type="string", length=600)
     */
    private $Content;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $Valide;

    /**
     * @Assert\Email(
     *     message = "L'email '{{ value }}' n'est pas valide."
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $Email;




    /**
     * Commentaire constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        $this->DateTime = new \DateTime('now');
        $this->Valide = false;

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): self
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->DateTime;
    }

    public function setDateTime(\DateTimeInterface $DateTime): self
    {
        $this->DateTime = $DateTime;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getValide(): ?bool
    {
        return $this->Valide;
    }

    public function setValide(?bool $Valide): self
    {
        $this->Valide = $Valide;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }





}

src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 * @Vich\Uploadable
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Lieu;

    /**
     * @ORM\Column(type="time", length=255, nullable=true)
     */
    private $Horaire;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Billeterie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Presentation;



    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string
     */
    private $Image;

    /**
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->Lieu;
    }

    public function setLieu(string $Lieu): self
    {
        $this->Lieu = $Lieu;

        return $this;
    }

    public function getHoraire(): ?\DateTimeInterface
    {
        return $this->Horaire;
    }

    public function setHoraire(?\DateTimeInterface $Horaire): self
    {
        $this->Horaire = $Horaire;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getBilleterie(): ?string
    {
        return $this->Billeterie;
    }

    public function setBilleterie(?string $Billeterie): self
    {
        $this->Billeterie = $Billeterie;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->Presentation;
    }

    public function setPresentation(string $Presentation): self
    {
        $this->Presentation = $Presentation;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

    }

    public function getImageFile()
    {
        return $this->imageFile;
    }
}

src/Entity/Music.php
<?php

namespace App\Entity;

use App\Repository\MusicRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MusicRepository::class)
 */
class Music
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=1500)
     */
    private $Embed;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmbed(): ?string
    {
        return $this->Embed;
    }

    public function setEmbed(string $Embed): self
    {
        $this->Embed = $Embed;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }
}

templates/index/contact.html.twig
{% extends ('base.html.twig') %}
    {% block body %}





        <section id="content">

            <div class="content-wrap">
                <div class="container clearfix">
                    <div class="row">
                        <div="col-12">
                            <h1>Nous  contacter</h1>
                            {{ form(contactForm) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            {{ form_start(formcom) }}
                            <form  action="include/form.php" method="post" enctype="multipart/form-data">
                                <div class="form-process"></div>
                                <div class="col-12 form-group">
                                    <div class="col-md-6 form-group">
                                        <label>Pseudo:</label>
                                        {{ form_widget (formcom.Pseudo) }}
                                    </div>
                                    <div class="col-md-6 form-group">
                                        <label>Email:</label>
                                        {{ form_widget (formcom.Email) }}
                                    </div>
                                    {# Tu as plusieur manière de faire des formulaires en twig, je te laisse te renseigner#}
                                    {#  https://symfony.com/doc/4.1/reference/forms/twig_reference.html#}
                                    {#            <div class="">#}
                                    {#                {{ form_label(ContactForm.Pseudo) }}#}
                                    {#            </div>#}
                                    {#            <div class="fadeIn second">#}
                                    {#                {{ form_widget(ContactForm.telephone) }}#}
                                    {#            </div>#}
                                    {#            <div class="erreur">#}
                                    {#                {{ form_errors(ContactForm.telephone) }}#}
                                    {#            </div>#}
                                    {{ form_widget (formcom.Content) }}
                                    {#Deux façon de mettre un boutton submit, soit dans le CommentaireType ou ici, a toi de choisir#}
                                    {# <button class="btn btn-primary mb-3" type="submit">Valider</button> #}
                                    {{ form_end(formcom) }}
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 form-group">
                            {% for comm in commentaires %}

                                {{ comm.pseudo }}
                                {{ comm.DateTime|date("d/m/Y")  }}
                                {{ comm.content|raw }}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </section>

    {% endblock %}

templates/index/liveagenda.html.twig
{% extends ('base.html.twig') %}
    {% block body %}

        <!-- Page Title
        ============================================= -->
        <section id="page-blog" class="img-bd-live">

            <div class="container clearfix">
                <h1 class="center text-white titre-bd">Live Agenda</h1>
            </div>

        </section><!-- #page-title end -->
        <!-- Content
        ============================================= -->
        <section id="content">
            <div class="content-wrap">
                <div class="container clearfix">
                    <div id="posts" class="events small-thumbs">
                        <div class="postcontent nobottommargin clearfix">
                            {% for event in events %}
                                <div class="entry clearfix cardEvent">
                                    <div class="entry-image">
                                        <a href="#">
                                            <img src="{{ asset("imagesArticles/" ~ event.image) }}"
                                                 alt="évenement_kat">
                                            <div class="entry-date">{{ event.date|date("d") }}
                                                <span>{{ event.date|format_datetime(pattern='LLLL',locale='fr') }}</span>
                                                <span>{{ event.date|format_datetime(pattern='r',locale='fr') }}</span>
                                            </div>
                                        </a>
                                    </div>
                                    <div class="entry-c">
                                        <div class="entry-title">
                                            <h2><a href="#">{{ event.titre }}</a></h2>
                                        </div>
                                        <ul class="entry-meta clearfix">
                                            <li><a href="#"><i class="icon-time"></i>{{ event.horaire|date("h:i") }}</a>
                                            </li>
                                            <li><a href="#"><i class="icon-map-marker2"></i>{{ event.lieu }}</a></li>
                                        </ul>
                                        <div class="entry-content">
                                            <p class="p-presentation">{{ event.presentation }}</p>
                                            {% if not event.billeterie %}
                                                <a class="button button-3d button-rounded button-leaf cursor_none" disabled="disabled">Gratuit</a>
                                            {% elseif  event.billeterie %}
                                                <a href="{{ event.billeterie|raw }}"
                                                   onclick="window.open(this.href); return false;"
                                                   class="button button-3d button-rounded button-blue"
                                                   disabled="disabled">Billeterie</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="sidebar nobottommargin col_last">
                            <div class="sidebar-widgets-wrap">
                                <div class="widget clearfix">
                                    <div class="widget clearfix">
                                        <h4>Dernière musique</h4>
                                        {% for music in musics %}
                                            {{ music.embed|raw }}
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="widget clearfix">
                                    <div class="widget clearfix">
                                        <h4>Dernier articles</h4>
                                    <div id="post-list-footer">
                                        {% for article in articles %}
                                            <div class="spost clearfix">
                                                <div class="entry-image">
                                                    <img src="{{ asset("imagesArticles/" ~ article.image) }}"
                                                         class="petiteImage" alt="...">
                                                </div>
                                                <div class="entry-c">
                                                    <div class="entry-title">
                                                        <h4><a href="{{ path('article', {id: article.id }) }}">{{ article.titre }}</a></h4>
                                                    </div>
                                                    <ul class="entry-meta">
                                                        <li>{{ article.date|format_datetime('full','none',locale='fr') }}</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="widget clearfix">
                                    <h4>Dernière vidéo</h4>
                                    {% for lastvideo in lastvideos %}
                                        {{ lastvideo.embed|raw }}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section><!-- #content end -->
    {% endblock %}

templates/index/music.html.twig
{% extends ('base.html.twig') %}
    {% block body %}
        <!-- Page Title
		============================================= -->
		<section id="page-blog" class="img-bd-music ">

			<div class="container clearfix " >
				<h1 class="center text-white titre-bd">Music</h1>
			</div>

		</section><!-- #page-title end -->

		<!-- Content
		============================================= -->
		<section id="content">

			<div class="content-wrap">

				<div class="container clearfix">

					<!-- Post Content
					============================================= -->
					<div class="postcontent nobottommargin clearfix">

						{% for music in musics %}
							<h3>{{music.titre}}</h3>

							{{ music.embed|raw }}
							<div class="divider divider-center"><i class="icon-cloud"></i></div>
						{% endfor %}


					</div><!-- .postcontent end -->
					<!-- Sidebar
					============================================= -->
					<section>
						<div class="sidebar nobottommargin col_last">
							<div class="sidebar-widgets-wrap">
								<div class="widget clearfix">
									<h4>Prochain concert</h4>
									{% for nextconcert in nextconcerts %}
										<div class="spost clearfix">
											<div class="entry-image">
												<img src="{{ asset("imagesArticles/" ~ nextconcert.image) }}" class="petiteImage" alt="...">
											</div>
											<div class="entry-c">
												<div class="entry-title">
													<h4><a href="{{ path('liveagenda') }}">{{ nextconcert.titre }}</a></h4>
												</div>
												<div class="entry-title">
													<h4><a href="{{ path('liveagenda') }}"><img src="images/icons/map-icon.png"
																		 style="width: 1em">{{ nextconcert.lieu }}</a></h4>
												</div>
												<ul class="entry-meta">
													<li>{{ nextconcert.date|format_datetime('full','none',locale='fr') }}</li>
												</ul>
											</div>
										</div>
									{% endfor %}
								</div>
								<div class="widget clearfix">
									<h4>Dernier articles</h4>
									<div id="post-list-footer">
										{% for article in articles %}
											<div class="spost clearfix">
												<div class="entry-image">
													<img src="{{ asset("imagesArticles/" ~ article.image) }}" class="petiteImage" alt="..."  >
												</div>
												<div class="entry-c">
													<div class="entry-title">
														<h4><a href="{{ path('news') }}">{{ article.titre }}</a></h4>
													</div>
													<ul class="entry-meta">
														<li>{{ article.date|format_datetime('full','none',locale='fr') }}</li>
													</ul>
												</div>
											</div>
										{% endfor %}
									</div>
								</div>
								<div class="widget clearfix">
									<h4>Dernière vidéo</h4>
									{% for lastvideo in lastvideos %}
										{{ lastvideo.embed|raw }}
									{% endfor %}
								</div>
							</div>
						</div>
					</section>
				</div>
			</div>
		</section><!-- #content end -->
	{% endblock %}

templates/index/video.html.twig
{% extends ('base.html.twig') %}
    {% block body %}

        <!-- Page Title
                ============================================= -->
        <section id="page-blog" class="img-bd-video">

            <div class="container clearfix">
                <h1 class="center text-white titre-bd">Vidéos</h1>
            </div>

        </section><!-- #page-title end -->

        <!-- Content
        ============================================= -->

        <section id="content">
            <div class="content-wrap">
                <div class="container clearfix">
                    <!-- Post Content
                    ============================================= -->
                    <div class="postcontent nobottommargin clearfix">
                        {% for video in videos %}
                            <h3>{{ video.titre }}</h3>

                            {{ video.embed|raw }}

                            <div class="divider divider-right"><i class="icon-heart"></i></div>
                        {% endfor %}
                    </div><!-- .postcontent end -->
                    <!-- Sidebar
                    ============================================= -->
                    <div class="sidebar nobottommargin col_last">
                        <div class="sidebar-widgets-wrap">
                            <div class="widget clearfix">
                                <div class="widget clearfix">
                                    <h4>Dernière musique</h4>
                                    {% for music in musics %}
                                        {{ music.embed|raw }}
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="widget clearfix">
                                <div class="widget clearfix">
                                    <h4>Prochain concert</h4>
                                    {% for nextconcert in nextconcerts %}
                                        <div class="spost clearfix">
                                            <div class="entry-image">
                                                <img src="{{ asset("imagesArticles/" ~ nextconcert.image) }}"
                                                     class="petiteImage" alt="...">
                                            </div>
                                            <div class="entry-c">
                                                <div class="entry-title">
                                                    <h4><a href="#">{{ nextconcert.titre }}</a></h4>
                                                </div>
                                                <div class="entry-title">
                                                    <h4><a href="#"><img src="images/icons/map-icon.png"
                                                                         style="width: 1em">{{ nextconcert.lieu }}</a></h4>
                                                </div>
                                                <ul class="entry-meta">
                                                    <li>{{ nextconcert.date|format_datetime('full','none',locale='fr') }}</li>
                                                </ul>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="widget clearfix">
                                <div class="widget clearfix">
                                    <h4>Dernier articles</h4>
                                    <div id="post-list-footer">
                                        {% for article in articles %}
                                            <div class="spost clearfix">
                                                <div class="entry-image">
                                                    <img src="{{ asset("imagesArticles/" ~ article.image) }}"
                                                         class="petiteImage" alt="...">
                                                </div>
                                                <div class="entry-c">
                                                    <div class="entry-title">
                                                        <h4><a href="#">{{ article.titre }}</a></h4>
                                                    </div>
                                                    <ul class="entry-meta">
                                                        <li>{{ article.date|format_datetime('full','none',locale='fr') }}</li>
                                                    </ul>
                                                </div>
                                            </div>

                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- .sidebar end -->
                </div>
            </div>
        </section><!-- #content end -->
    {% endblock %}