src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository", repositoryClass=ArticleRepository::class)
 * @Vich\Uploadable
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $Texte;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $SousTitre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string
     */
    private $Image;

    /**
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Date;

    /**
     * @ORM\OneToMany(targetEntity=CommentaireArticle::class, mappedBy="Article", orphanRemoval=true)
     */
    private $commentaireArticles;






    /**
     * Article constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        $this->Date = new \DateTime('now');
        $this->commentaireArticles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->Texte;
    }

    public function setTexte(string $Texte): self
    {
        $this->Texte = $Texte;

        return $this;
    }

    public function getSousTitre(): ?string
    {
        return $this->SousTitre;
    }

    public function setSousTitre(string $SousTitre): self
    {
        $this->SousTitre = $SousTitre;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @return Collection|CommentaireArticle[]
     */
    public function getCommentaireArticles(): Collection
    {
        return $this->commentaireArticles;
    }

    public function addCommentaireArticle(CommentaireArticle $commentaireArticle): self
    {
        if (!$this->commentaireArticles->contains($commentaireArticle)) {
            $this->commentaireArticles[] = $commentaireArticle;
            $commentaireArticle->setArticle($this);
        }

        return $this;
    }

    public function removeCommentaireArticle(CommentaireArticle $commentaireArticle): self
    {
        if ($this->commentaireArticles->contains($commentaireArticle)) {
            $this->commentaireArticles->removeElement($commentaireArticle);
            // set the owning side to null (unless already changed)
            if ($commentaireArticle->getArticle() === $this) {
                $commentaireArticle->setArticle(null);
            }
        }

        return $this;
    }

}

src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CommentaireRepository::class)
 */
class Commentaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=55)
     */
    private $Pseudo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateTime;

    /**
     * @ORM\Column(type="string", length=600)
     */
    private $Content;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $Valide;

    /**
     * @Assert\Email(
     *     message = "L'email '{{ value }}' n'est pas valide."
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $Email;




    /**
     * Commentaire constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        $this->DateTime = new \DateTime('now');
        $this->Valide = false;

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): self
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->DateTime;
    }

    public function setDateTime(\DateTimeInterface $DateTime): self
    {
        $this->DateTime = $DateTime;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getValide(): ?bool
    {
        return $this->Valide;
    }

    public function setValide(?bool $Valide): self
    {
        $this->Valide = $Valide;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }





}

src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 * @Vich\Uploadable
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Lieu;

    /**
     * @ORM\Column(type="time", length=255, nullable=true)
     */
    private $Horaire;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Billeterie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Presentation;



    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string
     */
    private $Image;

    /**
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->Lieu;
    }

    public function setLieu(string $Lieu): self
    {
        $this->Lieu = $Lieu;

        return $this;
    }

    public function getHoraire(): ?\DateTimeInterface
    {
        return $this->Horaire;
    }

    public function setHoraire(?\DateTimeInterface $Horaire): self
    {
        $this->Horaire = $Horaire;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getBilleterie(): ?string
    {
        return $this->Billeterie;
    }

    public function setBilleterie(?string $Billeterie): self
    {
        $this->Billeterie = $Billeterie;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->Presentation;
    }

    public function setPresentation(string $Presentation): self
    {
        $this->Presentation = $Presentation;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

    }

    public function getImageFile()
    {
        return $this->imageFile;
    }
}

src/Entity/Music.php
<?php

namespace App\Entity;

use App\Repository\MusicRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MusicRepository::class)
 */
class Music
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=1500)
     */
    private $Embed;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmbed(): ?string
    {
        return $this->Embed;
    }

    public function setEmbed(string $Embed): self
    {
        $this->Embed = $Embed;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }
}

src/Controller/NewsController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Commentaire;
use App\Entity\Event;
use App\Entity\Music;
use App\Entity\Video;
use App\Entity\CommentaireArticle;
use App\Repository\ArticleRepository;
use App\Form\CommentaireArticleType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;



class NewsController extends AbstractController
{
    /**
     * @Route("/news", name="news")
     *
     */
    public function show()
    {

        $article = $this->getDoctrine()->getRepository(Article::class)->Articles();
        $music = $this->getDoctrine()->getRepository(Music::class)->LastMusic();
        $lastvideo = $this->getDoctrine()->getRepository(Video::class)->LastVideo();
        $nextconcert = $this->getDoctrine()->getRepository(Event::class)->NextConcert();
        return $this->render('news/news.html.twig', [
            'articles' => $article,
            'musics' => $music,
            'lastvideos' => $lastvideo,
            'nextconcerts' => $nextconcert,
        ]);
    }

    /**
     * @Route("/news/show/{id}", name="article")
     */
    public function singleArticle(ArticleRepository $repo, $id, EntityManagerInterface $em, Request $request)
    {
        $CommentaireArticle = new CommentaireArticle();
        $commentForm = $this->createForm(CommentaireArticleType::class, $CommentaireArticle);
        $commentForm -> handleRequest($request);
        $article = $this->getDoctrine()->getRepository(Article::class)->findOneBy(['id'=>$id]);

        if ($commentForm->isSubmitted() && $commentForm->isValid()){
            $CommentaireArticle->setArticle($article);
            $this->addFlash('success','Le commentaire à bien été envoyé, il seras traité au plus vite');
            $em->persist($CommentaireArticle);
            $em->flush();
            return $this->redirectToRoute('article', array('id' => $id));
        }
        $article = $repo->find($id);
        $music = $this->getDoctrine()->getRepository(Music::class)->LastMusic();
        $lastvideo = $this->getDoctrine()->getRepository(Video::class)->LastVideo();
        $nextconcert = $this->getDoctrine()->getRepository(Event::class)->NextConcert();
        $repo = $this->getDoctrine()->getRepository(CommentaireArticle::class);
        $countvalide =$repo->findBy(array('Valide'=>1, 'Article'=>$id));
        $CommentaireArticle = new CommentaireArticle();
        $form = $this->createForm(CommentaireArticleType::class, $CommentaireArticle);

        return $this->render('news/article.html.twig', [
            'countvalide' => $countvalide,
            'article' => $article,
            'form' => $form->createView(),
            'musics' => $music,
            'lastvideos' => $lastvideo,
            'nextconcerts' => $nextconcert,

        ]);
    }

}

templates/news/article.html.twig
{% extends ('base.html.twig') %}
    {% block body %}


        <!-- Page Title
        ============================================= -->
        <section id="page-blog" class="img-bd-article">

        </section>
        <!-- Content
        ============================================= -->

        <section id="content">
            <div class="content-wrap">
                <div class="container clearfix">
                    <!-- Post Content
                    ============================================= -->
                    <div class="postcontent nobottommargin clearfix">
                        <div class="single-post nobottommargin">
                            <!-- Single Post
                            ============================================= -->
                            <div class="entry clearfix">
                                <!-- Entry Title
                                ============================================= -->
                                <div class="entry-title">
                                    <h1>{{ article.titre }}</h1>
                                </div><!-- .entry-title end -->
                                <h3>{{ article.SousTitre }}</h3>

                                <!-- Entry Meta
                                ============================================= -->
                                <ul class="entry-meta clearfix">
                                    <li><i class="icon-calendar3"></i> {{ article.date|format_datetime('full','none',locale='fr') }}</li>

                                </ul><!-- .entry-meta end -->

                                <!-- Entry Image
                                ============================================= -->
                                <div class="articleImg">
                                    <img src="{{ asset("imagesArticles/" ~ article.image) }}"
                                         alt="Blog Single">
                                </div><!-- .entry-image end -->

                                <!-- Entry Content
                                ============================================= -->
                                <div class="entry-content notopmargin">

                                    <p>{{ article.texte|raw }}</p>

                                </div>
                            </div><!-- .entry end -->


                            <div class="divider divider-rounded divider-right"><i class="icon-chat"></i></div>
                            <!-- Comments List
                            ============================================= -->
                            <h3 class="comments-title"><span>{{ countvalide|length }}</span>
                                Commentaires</h3>

                            {% for commentaireArticle in article.commentaireArticles %}
                            {% if commentaireArticle.valide == 1 %}
                            <ol class="commentlist clearfix">
                                <li class="comment even thread-even depth-1" id="li-comment-1">
                                    <div id="comment-1" class="comment-wrap clearfix mb-3">
                                        <div class="comment-meta">
                                            <div class="comment-author vcard">
                                                <span class="comment-avatar clearfix">
                                                    <script type="text/javascript"
                                                            language="javascript">document.write('' +
                                                            '<img class="avatar avatar-60 photo avatar-default" height="60" width="60" ' +
                                                            'src="{{ asset("images_kat/icon_commentaire/") }}' + Math.round((Math.random() * 8) + 1) + '.png" />');
                                                            </script>
                                                </span>
                                            </div>
                                        </div>
                                        <div class="comment-content clearfix">
                                            <div class="comment-author">{{ commentaireArticle.pseudo }}<span>
                                                    <a title="Permalink to this comment">{{ commentaireArticle.createdAt|format_datetime('full','none',locale='fr') }}</a></span>
                                            </div>

                                            <p>{{ commentaireArticle.content|raw }}</p>

                                            <a class="comment-reply-link" href="#"><i class="icon-reply"></i></a>
                                        </div>
                                        <div class="clear  "></div>
                                    </div>
                                </li>
                                {% endif %}
                                {% endfor %}
                            </ol><!-- .commentlist end -->

                            <div class="divider divider-sm divider-rounded divider-center"><i class="icon-pencil"></i>
                            </div>

                            <!-- Comment Form
                            ============================================= -->


                            <div id="respond" class="clearfix">

                                <h3 class="comments-title">Laissez un <span>Commentaire</span></h3>

                                <form class="clearfix" action="#" method="post" id="commentform">
                                    {{ form_start(form) }}

                                    <div class="row">
                                        <div class="col-lg-4 ">
                                            {{ form_label(form.Pseudo) }}
                                            {{ form_widget(form.Pseudo) }}
                                        </div>
                                        <div class="col-lg-4 ">
                                            {{ form_label(form.Email) }}
                                            {{ form_widget(form.Email) }}
                                        </div>
                                    </div>
                                    <div class="row ">
                                        <div class="col-lg-12 mt-5 ">
                                            {{ form_widget(form.Content) }}
                                        </div>
                                    </div>
                                    <div class="col-lg-4 mt-3 mr-5">
                                        <button name="submit" type="submit" id="submit-button" tabindex="5"
                                                value="Submit"
                                                class="button button-3d button-xlarge button-rounded button-amber ">
                                            Publier
                                        </button>
                                    </div>
                                    {{ form_end(form) }}
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- Sidebar
                        ============================================= -->
                    <div class="sidebar nobottommargin col_last clearfix">
                        <div class="sidebar-widgets-wrap">
                            <div class="widget clearfix">
                                <div class="widget clearfix">
                                    <h3>Dernière musique</h3>
                                    {% for music in musics %}
                                        {{ music.embed|raw }}
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="widget clearfix">
                                <h3>Prochain concert</h3>
                                {% for nextconcert in nextconcerts %}
                                    <div class="spost clearfix">
                                        <div class="entry-image">
                                            <img src="{{ asset("imagesArticles/" ~ nextconcert.image) }}"
                                                 class="petiteImage" alt="...">
                                        </div>
                                        <div class="entry-c">
                                            <div class="entry-title">
                                                <h4><a href="#">{{ nextconcert.titre }}</a></h4>
                                            </div>
                                            <div class="entry-title">
                                                <h4><img src="{{ asset("images/icons/map-icon-red.png") }}"
                                                         style="width: 1em">{{ nextconcert.lieu }}</h4>
                                            </div>
                                            <ul class="entry-meta">
                                                <li>{{ nextconcert.date|format_datetime('full','none',locale='fr') }}</li>
                                            </ul>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="widget clearfix">
                                <h3>Dernière vidéo</h3>
                                {% for lastvideo in lastvideos %}
                                    {{ lastvideo.embed|raw }}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section><!-- #content end -->
    {% endblock %}

templates/news/news.html.twig
{% extends ('base.html.twig') %}

{% block body %}

    <!-- Page Title
        ============================================= -->
    <section id="page-blog" class="img-bd-news">

        <div class="container clearfix">
            <h1 class="center text-white titre-bd">News</h1>
        </div>

    </section><!-- #page-title end -->

    <section id="content">

        <div class="content-wrap">

            <div class="container clearfix">

                <!-- Post Content
                ============================================= -->
                <div class="postcontent nobottommargin clearfix">
                    <!-- Posts
                    ============================================= -->
                    <div id="posts" class="small-thumbs">
                        {% for article in articles %}
                            <div class="entry clearfix">
                                <div class="entry-image">
                                    <img src="{{ asset("imagesArticles/" ~ article.image) }}"
                                         class="card-img-top image-menu" alt="...">
                                </div>
                                <div class="entry-c">
                                    <div class="entry-title">
                                        <h1><a href="{{ path('article', {id: article.id }) }}">{{ article.Titre }}</a>
                                        </h1>
                                        <h2>{{ article.SousTitre }}</h2>
                                    </div>
                                    <ul class="entry-meta clearfix">
                                        <li>
                                            <i class="icon-calendar3"></i> {{ article.date|format_datetime('full','none',locale='fr') }}
                                        </li>
                                        <li><i class="icon-comment"> {{ article.commentaireArticles|length }}</i></li>
                                    </ul>
                                    <div class="entry-content">
                                        {% if article.Texte|length < 250 %}
                                            <p class="mt-0">{{ article.Texte|slice(0, 250)|raw }}</p>
                                        {% elseif article.Texte|length > 250 %}
                                            <p class="mt-0">{{ article.Texte|slice(0, 250)|raw }}...</p>
                                        {% endif %}
                                        <a href="{{ path('article', {id: article.id }) }}" class="more-link ">Lire la
                                            suite</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div><!-- #posts end -->
                </div><!-- .postcontent end -->
                <!-- Sidebar
                ============================================= -->
                <div class="sidebar nobottommargin col_last clearfix">
                    <div class="sidebar-widgets-wrap">
                        <div class="widget clearfix">
                            <div class="widget clearfix">
                                <h3>Dernière musique</h3>
                                {% for music in musics %}
                                    {{ music.embed|raw }}
                                {% endfor %}
                            </div>
                        </div>
                        <div class="widget clearfix">
                            <h3>Prochain concert</h3>
                            {% for nextconcert in nextconcerts %}
                                <div class="spost clearfix">
                                    <div class="entry-image">
                                        <img src="{{ asset("imagesArticles/" ~ nextconcert.image) }}"
                                             class="petiteImage" alt="...">
                                    </div>
                                    <div class="entry-c">
                                        <div class="entry-title">
                                            <h4><a href="#">{{ nextconcert.titre }}</a></h4>
                                        </div>
                                        <div class="entry-title">
                                            <h4><a href="#"><img src="images/icons/map-icon-red.png"
                                                                 style="width: 1em">{{ nextconcert.lieu }}</a></h4>
                                        </div>
                                        <ul class="entry-meta">
                                            <li>{{ nextconcert.date|format_datetime('full','none',locale='fr') }}</li>
                                        </ul>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="widget clearfix">
                            <h3>Dernière vidéo</h3>
                            {% for lastvideo in lastvideos %}
                                {{ lastvideo.embed|raw }}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section><!-- #content end -->
    <!-- Footer
    ============================================= -->

    <!-- Content
    ============================================= -->
    {#		<section id="content">#}

    {#			<div class="content-wrap">#}

    {#				<div class="container clearfix">#}

    {#					<!-- Posts#}
    {#					============================================= -->#}
    {#					<div id="posts">#}

    {#						{% for article in articles %}#}
    {#							<h2><a href="blog-single-full.html">{{ article.Titre }}</a></h2>#}
    {#							{{ article.Titre }}#}
    {#							{{ article.SousTitre }}#}
    {#							{{ article.Texte|raw }}#}
    {#							<img src="{{ asset("imagesArticles/" ~ article.image) }}" class="card-img-top image-menu" alt="...">#}
    {#							{{ article.date|date("d/mmmm/Y") }}	#}
    {#			#}
    {#						{% endfor %}#}
    {#						</div>#}

    {#					  #}
    {#					<!-- .pager end -->#}

    {#				</div>#}

    {#			</div>#}

    {#		</section><!-- #content end -->#}

{% endblock %}